# Generated by Django 3.0.7 on 2020-06-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockplatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('buyer_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('description', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='transaction_key',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mockplatform.PlatformUser'),
        ),
    ]
