# Generated by Django 3.0.7 on 2020-06-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockplatform', '0002_auto_20200622_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction_status',
            field=models.CharField(choices=[('C', 'CREATED'), ('I', 'IN PROCESS'), ('S', 'SUCCESS'), ('F', 'FAILED')], default='C', max_length=1),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
