# Generated by Django 3.0.7 on 2020-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockplatform', '0002_auto_20200622_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
        migrations.DeleteModel(
            name='PlatformUser',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
