# Generated by Django 3.0.7 on 2020-06-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockplatform', '0004_auto_20200624_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction_status',
            field=models.CharField(choices=[('C', 'CREATED'), ('I', 'IN PROCESS'), ('S', 'SUCCESS'), ('F', 'FAILED')], default='C', max_length=1),
        ),
    ]
