# Generated by Django 3.0.7 on 2020-06-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockplatform', '0005_invoice_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='SGD', max_length=3),
        ),
    ]
