# Generated by Django 3.0.7 on 2020-06-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockplatform', '0007_auto_20200625_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
