# Generated by Django 3.0.7 on 2020-06-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockplatform', '0008_invoice_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(default='', max_length=150),
        ),
    ]
