# Generated by Django 3.0.7 on 2020-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockplatform', '0010_auto_20200625_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='seller_id',
            field=models.CharField(max_length=100),
        ),
    ]
